datini/datini/urls.py
from django.urls import path, include, re_path
from django.views.i18n import JavaScriptCatalog

from base.views import home, font
from expense.views.expense import manifest

urlpatterns = [
    path('', home, name='home'),
    path('font.css', font, name='font'),
    path('account/', include("account.urls")),
    path('invite/', include("invite.urls")),
    path("manifest.json", manifest, name="manifest"),
    path("expense/", include("expense.urls")),
    path("takeout/", include("takeout.urls")),
]

# jsi18n can be anything you like here
urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['recurrence']), name="javascript-catalog"),
]

datini/takeout/urls.py
from django.urls import path

from . import views

app_name = "takeout"
urlpatterns = [
    path("", view=views.index, name="index"),
    path("takeout/", view=views.takeout, name="takeout"),
    path("backup/", view=views.backup, name="backup"),
]

datini/takeout/views.py
from io import BytesIO

from django.http import StreamingHttpResponse, HttpResponse
from django.template.response import TemplateResponse
from django.utils import timezone

from base.views import clan_required
from .methods import create_backup_file, get_csv


@clan_required
def index(request):
    return TemplateResponse(request, template="takeout.html")


@clan_required
def takeout(request):
    filename = f"datini-takeout-{timezone.now():%Y%m%d%H%M%S}.csv"
    return StreamingHttpResponse(
        get_csv(clan=request.user.clan),
        content_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@clan_required
def backup(request):
    filename = f"datini-backup-{timezone.now():%Y%m%d%H%M%S}.zip"
    zip_handler = BytesIO()
    create_backup_file(zip_handler)
    return HttpResponse(zip_handler.getvalue(),
                        content_type="application/zip",
                        headers={"Content-Disposition": f'attachment; filename="{filename}"'})

datini/takeout/templates/takeout.html
{% extends 'account/base.html' %}
{% load ftl %}
{% load django_bootstrap5 %}

{% block head %}
	{{ block.super }}
  <style>
    .datini-takeout-container {
      display: flex;
      align-items: center;
      margin-bottom: 1rem;
      padding: .5rem;
      border-radius: var(--bs-border-radius);
      background-color: var(--bs-light);

      h2 {
        margin-bottom: 0;
      }

      .datini-takeout-action-def {
        flex-basis: 66%;
      }
      .datini-takeout-action {
        margin-left: auto;
        min-width: 10rem;
        text-align: center;
      }
    }
  </style>
{% endblock %}

{% block main %}
  {% ftlconf mode="server" bundle="takeout.fluent.bundle" %}

	<div class="container">
    <h1>
      {% ftlmsg "takeout-title" %}
    </h1>
    <p>
      {% ftlmsg "takeout-help" %}
    </p>
    <form action="{% url "takeout:takeout" %}" method="get" class="datini-takeout-container">
      <section class="datini-takeout-action-def">
        <h2>{% ftlmsg "takeout-spreadsheet-action" %}</h2>
        <p>{% ftlmsg "takeout-spreadsheet-subtitle" %}</p>
        <p class="form-text">
          {% ftlmsg "takeout-spreadsheet-help" %}
        </p>
      </section>
      <section class="datini-takeout-action">
        <button type="submit" class="btn btn-primary">
          {% ftlmsg "takeout-spreadsheet-action" %}
        </button>
      </section>
    </form>

    <form action="{% url "takeout:backup" %}" method="get" class="datini-takeout-container">
      <section class="datini-takeout-action-def">
        <h2>{% ftlmsg "takeout-backup-action" %}</h2>
        <p>{% ftlmsg "takeout-backup-subtitle" %}</p>
        <p class="form-text">
          {% ftlmsg "takeout-backup-help" %}
        </p>
      </section>
      <section class="datini-takeout-action">
        <button type="submit" class="btn btn-primary">
          {% ftlmsg "takeout-backup-action" %}
        </button>
      </section>
    </form>

  </div>
{% endblock %}