datini/account/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "account"
urlpatterns = [
    # Getting into your account
    path("login", view=views.LoginView.as_view(), name="login"),
    path("logout", view=LogoutView.as_view(), name="logout"),
    path("reset_password", view=views.reset_password, name="reset_password"),
    path("reset_password/sent/", view=views.reset_password_sent, name='reset_password_sent'),
    path("reset_password/new/<uidb64>/<token>/", view=views.reset_password_new, name='reset_password_new'),
    path("reset_password/done/", view=views.reset_password_done, name='reset_password_done'),
    path("profile", view=views.profile, name="profile"),
    path("clan", view=views.clan, name="clan"),
    path("clan/join", view=views.clan_join, name="clan_join"),
    path("clan/create", view=views.clan_create, name="clan_create"),
    path("clan/update", view=views.clan_update, name="clan_update"),
]

datini/datini/urls.py
from django.urls import path, include, re_path
from django.views.i18n import JavaScriptCatalog

from base.views import home, font
from expense.views.expense import manifest

urlpatterns = [
    path('', home, name='home'),
    path('font.css', font, name='font'),
    path('account/', include("account.urls")),
    path('invite/', include("invite.urls")),
    path("manifest.json", manifest, name="manifest"),
    path("expense/", include("expense.urls")),
    path("takeout/", include("takeout.urls")),
]

# jsi18n can be anything you like here
urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['recurrence']), name="javascript-catalog"),
]

datini/expense/urls.py
from django.urls import path

from .views.expense import create_expense, all_expenses, home, update_expense, manifest, cancel_expense, restore_expense
from .views.recurring_expense import list_items, create_recurring_expense, update_recurring_expense

app_name = "expense"
urlpatterns = [
    path("", home, name="home"),
    path("create/", create_expense, name="create"),
    path("all/", all_expenses, name="all"),
    path("expense.webmanifest", manifest, name="manifest"),
    path("recurring/<pk>/update", update_recurring_expense, name="recurring_update"),
    path("<pk>/update", update_expense, name="update"),
    path("<pk>/cancel", cancel_expense, name="cancel"),
    path("<pk>/restore", restore_expense, name="restore"),
    
    path("recurring/", list_items, name="recurring_list"),
    path("recurring/create/", create_recurring_expense, name="recurring_create"),
    
]

datini/base/models.py
import nanoid
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField, ForeignKey, PROTECT, BigAutoField


def generate():
    return nanoid.generate('abcdefghijklmnopqrstuvwxyz0123456789', size=10)


class UserManager(BaseUserManager):
    """ To be used in conjunction with our custom User model that has
        the email field as the primary identifier.
    """

    def create_user(self, *args, **extra_field):
        """ Createsuperuser calls this method with (email, password, **extra_field).
            Socialauth pipeline calls this method with (email=email, password=password)
        """
        try:
            email, password = args
        except ValueError:
            email = extra_field.pop('email', None)
            password = extra_field.pop('password', None)

        if not email:
            raise ValueError("Email is required")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_field)
        if password:
            user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.update(is_staff=True, is_superuser=True, is_active=True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    """ Overwrites the base User model's id field using a varchar instead of a auto increment
        and using email as the primary unique key.
    """
    id = BigAutoField(primary_key=True)
    username = None
    email = EmailField("Email", unique=True)
    clan = ForeignKey("account.Clan", on_delete=PROTECT, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def full_name(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}"
        else:
            return self.email.split("@")[0]

    @property
    def name(self):
        if self.first_name:
            return self.first_name
        else:
            return self.email.split("@")[0]

    def __str__(self):
        return self.full_name

datini/base/views.py
from django.contrib.auth.decorators import user_passes_test
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView

font = TemplateView.as_view(template_name="base/font.css", content_type="text/css")
home = TemplateView.as_view(template_name="home/home.html")
clan_required = user_passes_test(lambda u: u.is_authenticated and u.clan is not None, login_url=reverse_lazy("account:clan"))

datini/base/templates/base/base.html
{% load static %}
{% load ftl %}
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="{{ request.LANGUAGE_CODE }}">
<head>
  <meta charset="UTF-8" />
  <link rel="icon" href="{% static "home/favicon.svg" %}">
  <link rel=”mask-icon” href="{% static "home/mask-icon.svg" %}" color="#000000">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="msapplication-TileColor" content="#426a5a" />
  <meta name="theme-color" content="#426a5a" />
  {% block head %}{% endblock head %}
  <title>Datini{% if title %} - {{title}}{% endif %}</title>
  <link rel="stylesheet" href="{% url 'font' %}" />
  <link rel="stylesheet" href="{% static 'bootstrap.css' %}" />
  {% bootstrap_javascript %}
</head>

<body class="min-vh-100 d-flex flex-column">
  {% block nav %}
  {% ftlconf mode="server" bundle="base.fluent.bundle" %}
  <nav class="navbar navbar-expand bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand me-auto" href="{% url "home" %}">Datini</a>
      <ul class="navbar-nav">
      {% if request.user.is_anonymous %}
        <li class="nav-item">
          <a href="{% url "account:login" %}" class="btn btn-outline-primary">{% ftlmsg "nav-start-now" %}</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a href="{% url "expense:home" %}" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-columns" viewBox="0 0 16 16">
              <path fill-rule="evenodd" d="M0 .5A.5.5 0 0 1 .5 0h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 0 .5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-13 2A.5.5 0 0 1 .5 2h8a.5.5 0 0 1 0 1h-8a.5.5 0 0 1-.5-.5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-13 2A.5.5 0 0 1 .5 4h10a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-13 2A.5.5 0 0 1 .5 6h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-13 2A.5.5 0 0 1 .5 8h7a.5.5 0 0 1 0 1h-7a.5.5 0 0 1-.5-.5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-13 2a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-13 2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m-13 2a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H.5a.5.5 0 0 1-.5-.5m13 0a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5"/>
            </svg>
            <span class="d-none d-sm-inline">{% ftlmsg "nav-expenses" %}</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url "account:profile" %}" class="btn btn-outline-primary">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
              <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3Zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z"/>
            </svg>
            <span class="d-none d-sm-inline">{{ request.user }}</span>
          </a>
        </li>
        {% endif %} 
      </ul>
    </div>
  </nav>
  {% endblock nav %}

  {% block header %}{% endblock header %}
  <main class="flex-grow-1">
    {% block main %} {% endblock main %}
  </main>
  <footer class="container-fluid bg-body-tertiary mt-5">
    <div class="container">
      <div class="row row-cols-2 row-cols-md-4 flex-wrap small text-center">
      {% block footer %}
        <div>
          <a href="#" class="text-secondary py-4 px-2 d-block">
            Cos'è Datini
          </a>
        </div>
        <div>
          <a href="#" class="text-secondary py-4 px-2 d-block">
            Chi era Datini
          </a>
        </div>
        <div>
          <a href="#" class="text-secondary py-4 px-2 d-block">
            Prezzi
          </a>
        </div>
        <div>
          <a href="#" class="text-secondary py-4 px-2 d-block">
            Privacy
          </a>
        </div>
      {% endblock footer %}
      </div>
    </div>
  </footer>
</body>

</html>

datini/base/templates/base/paginator_controls.html
{% load ftl %}

{% ftlconf mode="server" bundle="base.fluent.bundle" %}

<div class="d-flex align-items-center">
  <div class="me-auto">
    {% ftlmsg 'base-pagination' number=number num_pages=num_pages %}
  </div>
  <div class="btn-group" role="group">
    <a class="btn btn-outline-primary btn-sm {% if has_previous %}btn-gray-dark{% else %}btn-gray disabled{% endif %}" {% if has_previous %}href="{{ previous_url }}"{% endif %}>Indietro</a>
    <a class="btn btn-outline-primary btn-sm {% if has_next %}btn-gray-dark{% else %}btn-gray disabled{% endif %}" {% if has_next %}href="{{ next_url }}"{% endif %}>Avanti</a>
  </div>
</div>