datini/datini/urls.py
from django.urls import path, include, re_path
from django.views.i18n import JavaScriptCatalog

from base.views import home, font
from expense.views.expense import manifest

urlpatterns = [
    path('', home, name='home'),
    path('font.css', font, name='font'),
    path('account/', include("account.urls")),
    path('invite/', include("invite.urls")),
    path("manifest.json", manifest, name="manifest"),
    path("expense/", include("expense.urls")),
    path("takeout/", include("takeout.urls")),
]

# jsi18n can be anything you like here
urlpatterns += [
    path('jsi18n/', JavaScriptCatalog.as_view(packages=['recurrence']), name="javascript-catalog"),
]

datini/expense/urls.py
from django.urls import path

from .views.expense import create_expense, all_expenses, home, update_expense, manifest, cancel_expense, restore_expense
from .views.recurring_expense import list_items, create_recurring_expense, update_recurring_expense

app_name = "expense"
urlpatterns = [
    path("", home, name="home"),
    path("create/", create_expense, name="create"),
    path("all/", all_expenses, name="all"),
    path("expense.webmanifest", manifest, name="manifest"),
    path("recurring/<pk>/update", update_recurring_expense, name="recurring_update"),
    path("<pk>/update", update_expense, name="update"),
    path("<pk>/cancel", cancel_expense, name="cancel"),
    path("<pk>/restore", restore_expense, name="restore"),
    
    path("recurring/", list_items, name="recurring_list"),
    path("recurring/create/", create_recurring_expense, name="recurring_create"),
    
]

datini/expense/views/expense.py
from urllib.parse import urlencode

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Sum
from django.forms import DateTimeInput, ModelForm, CharField, HiddenInput, Form, RadioSelect, ModelChoiceField, \
    modelform_factory
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_http_methods

from account.models import Clan
from base.views import clan_required
from base.templatetags.paginator_controls import paginator_controls
from expense.fluent import bundle
from expense.models import Expense

_ = bundle.format
User = get_user_model()
EXPENSE_ALL_PARAMS_KEY = "expense-all-params"


def get_user_label(user):
    if user.first_name and user.last_name:
        return f"{user.first_name} {user.last_name[0]}."
    elif user.last_name:
        return f"{user.last_name}"
    elif user.first_name:
        return f"{user.first_name}"
    else:
        return "{}".format(user.email.split("@")[0])


class HTMLDateTimeInput(DateTimeInput):
    input_type = "datetime-local"
    
    def format_value(self, value):
        return "{:%Y-%m-%dT%H:%M}".format(value) if value else ""


class SearchForm(Form):
    q = CharField(min_length=3)


class UserChoiceField(ModelChoiceField):

    def label_from_instance(self, obj):
        return get_user_label(obj)


@login_required
@clan_required
def create_expense(request):
    form_class = get_expense_form(request.user)
    next = request.GET.get('next', reverse("expense:home"))
    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.clan = request.user.clan
            expense.save()
            messages.add_message(request, messages.SUCCESS, _("expense-created"))
            return redirect(form.cleaned_data['next'])
    else:
        form = form_class(initial={'next': next,
                                   'who': request.user,
                                   'how_much': (None, "EUR")})
    
    context = {'form': form, 'next': next}
    return render(request, "expense/create.html", context)


def get_expense_form(user):
    class ExpenseForm(ModelForm):
        next = CharField(widget=HiddenInput)
        who = UserChoiceField(queryset=User.objects.filter(clan=user.clan, is_active=True),
                                    label=_("expense-who"))

    form_fields = ("next", "who", "what", "how_much", "category", "when")
    form_labels = {
        "who": _("expense-who").title(),
        "what": _("expense-what").title(),
        "how_much": _("expense-how_much").title(),
        "category": _("expense-category").title(),
        "when": _("expense-when").title(),
    }
    form_widgets = {
        'when': HTMLDateTimeInput,
        'category': RadioSelect
    }

    form_class = modelform_factory(Expense,
                                   ExpenseForm,
                                   fields=form_fields,
                                   labels=form_labels,
                                   widgets=form_widgets)
    return form_class


@login_required
@clan_required
def all_expenses(request):
    queryset = Expense.all_objects.filter(clan=request.user.clan).order_by("-when")
    paginate_by = 10
    list_params = {}
    
    search_text = request.GET.get('search')
    if search_text:
        queryset = queryset.filter(what__icontains=search_text)
        list_params['search'] = search_text

    paginator = Paginator(queryset, paginate_by)
    page_obj = paginator.get_page(request.GET.get('page'))
    if page_obj.number != 1:
        list_params['page'] = page_obj.number
        
    controls = paginator_controls(request, page_obj)

    context = {
        'expense_list': [{
            "pk": expense.pk,
            "who": expense.who,
            "what": expense.what,
            "how_much": expense.how_much,
            "get_category_display": expense.get_category_display(),
            "when": expense.when,
            "is_yours": expense.who == request.user,
            "is_canceled": expense.deleted_at is not None
        } for expense in page_obj.object_list],
        'paginator': paginator,
        'page_obj': page_obj,
        **controls
    }
    request.session[EXPENSE_ALL_PARAMS_KEY] = list_params
    return render(request, "expense/list.html", context)


@login_required
@clan_required
def home(request):
    clan = Clan.objects.get(user=request.user)
    users = User.objects.filter(clan=clan, is_active=True)
    split_by = users.count()
    queryset = Expense.all_objects.filter(clan=request.user.clan).order_by("-when")

    expenses = Expense.objects.filter(clan=clan)
    totals = {item['who']: item['total'] for item in expenses.values("who").annotate(total=Sum('how_much'))}
    grand_total = Expense.objects.filter(clan=request.user.clan).aggregate(total=Sum('how_much'))['total']
    members = sorted([{
        'title': get_user_label(user),
        'is_self': user == request.user,
        'total': totals.get(user.pk, 0.0),
        'difference': grand_total / split_by - totals[user.pk] if user.pk in totals else None
    } for user in users], key=lambda item: not item['is_self'])

    context = {
        'clan': clan,
        'members': members,
        'expense_list': [{
            "pk": expense.pk,
            "who": expense.who,
            "what": expense.what,
            "how_much": expense.how_much,
            "get_category_display": expense.get_category_display(),
            "when": expense.when,
            "is_yours": expense.who == request.user,
            "is_canceled": expense.deleted_at is not None
        } for expense in queryset[:15]]
    }
    return render(request, "expense/home.html", context=context)


@login_required
@clan_required
def update_expense(request, pk):
    expense = get_object_or_404(Expense.all_objects, pk=pk)
    form_class = get_expense_form(request.user)
    next_url = request.GET.get('next', reverse("expense:home"))
    list_params = request.session.get(EXPENSE_ALL_PARAMS_KEY)
    if list_params:
        next_url = f"{next_url}?{urlencode(list_params)}"

    if request.method == "POST":
        form = form_class(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, _("expense-created"))
            return redirect(form.cleaned_data['next'])
    else:
        form = form_class(initial={'next': next_url}, instance=expense)
    
    context = {'form': form, 'next': next_url, 'pk': pk, 'is_deleted': expense.deleted_at is not None}
    return render(request, "expense/update.html", context)


@cache_control(max_age=86_400)
def manifest(request):
    context = {
        'start_url': request.build_absolute_uri(reverse("expense:home")),
        'shortcut_create_name': bundle.format('expense-create')
    }
    return render(request, "expense/expense.webmanifest", context=context, content_type="application/manifest+json")


@require_http_methods(["POST"])
@login_required
@clan_required
def cancel_expense(request, pk):
    expense = get_object_or_404(Expense, pk=pk)
    next_url = request.POST.get('next', reverse("expense:home"))
    expense.soft_delete()
    messages.add_message(request, messages.SUCCESS, _("expense-deleted"))
    return redirect(next_url)


@require_http_methods(["POST"])
@login_required
@clan_required
def restore_expense(request, pk):
    expense = get_object_or_404(Expense.all_objects, pk=pk)
    next_url = request.POST.get('next', reverse("expense:home"))
    expense.restore()
    messages.add_message(request, messages.SUCCESS, _("expense-restored"))
    return redirect(next_url)

datini/expense/views/recurring_expense.py
import zoneinfo
import datetime
from urllib.parse import urlencode

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.forms import ModelChoiceField, RadioSelect, modelform_factory, ModelForm, HiddenInput, CharField, \
    ChoiceField
from django.forms import DateTimeInput
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from base.views import clan_required
from expense.methods import get_next_occurrence, create_current_expenses
from expense.models import RecurringExpense
from expense.fluent import bundle

_ = bundle.format
User = get_user_model()
RECURRING_EXPENSE_PARAMS_KEY = 'recurring-expense-params'



class HTMLTimeInput(DateTimeInput):
    input_type = "time"
    
    def format_value(self, value):
        return "{:%H:%M}".format(value) if value else ""


class RecurringExpenseForm(ModelForm):
    next = CharField(widget=HiddenInput)


@login_required
@clan_required
def list_items(request):
    queryset = RecurringExpense.objects.filter(clan=request.user.clan).order_by("-created_by")
    list_params = {}
    
    search_text = request.GET.get('search')
    if search_text:
        queryset = queryset.filter(what__icontains=search_text)
        list_params['search'] = search_text
    
    
    context = {
        'item_list': [{
            "pk": item.pk,
            "who": item.who,
            "what": item.what,
            "how_much": item.how_much,
            "get_category_display": item.get_category_display(),
            "is_yours": item.who == request.user,
            "next_occurrence": item.next_occurrence,
            "time_zone": zoneinfo.ZoneInfo(item.time_zone)
        } for item in queryset]
    }
    request.session[RECURRING_EXPENSE_PARAMS_KEY] = list_params
    return render(request, "recurring_expense/list.html", context)


@login_required
@clan_required
def create_recurring_expense(request):
    form_class = get_recurring_expense_form(request.user)
    next = request.GET.get('next', reverse("expense:recurring_list"))
    if request.method == "POST":
        form = form_class(request.POST)
        if form.is_valid():
            rexpense = form.save(commit=False)
            rexpense.clan = request.user.clan
            rexpense.next_occurrence = get_next_occurrence(rexpense.recurrences,
                                                           time=rexpense.time,
                                                           time_zone=rexpense.time_zone)
            rexpense.save()
            messages.add_message(request, messages.SUCCESS, _("expense-created"))
            return redirect(form.cleaned_data['next'])
    else:
        form = form_class(initial={'next': next,
                                   'who': request.user,
                                   'how_much': (None, "EUR")})
    
    context = {
        'form': form,
        'next': next,
        #'default_recurrence_time': RecurringExpense._meta.get_field('time').default
        'default_recurrence_time': f"{RecurringExpense._meta.get_field('time').default:%H:%M}"
    }
    return render(request, "recurring_expense/create.html", context)


def get_recurring_expense_form(user):
    form_fields = ("next", "who", "what", "how_much", "category",
                   "recurrences", "time", "time_zone")
    form_labels = {
        "who": _("expense-who").title(),
        "what": _("expense-what").title(),
        "how_much": _("expense-how_much").title(),
        "category": _("expense-category").title(),
        "time": _("expense-recurrences-time"),
        "recurrences": _("expense-recurrences").title(),
        "time_zone": _("expense-recurrences-time-zone").title()
    }
    form_widgets = {
        'category': RadioSelect,
        'time': HTMLTimeInput
    }
    
    def formfield_for_dbfield(db_field, **kwargs):
        if db_field.name == "who":
            return ModelChoiceField(queryset=User.objects.filter(clan=user.clan, is_active=True),
                                    label=_("expense-who"))
        return db_field.formfield(**kwargs)
    
    form_class = modelform_factory(RecurringExpense,
                                   RecurringExpenseForm,
                                   fields=form_fields,
                                   labels=form_labels,
                                   formfield_callback=formfield_for_dbfield,
                                   widgets=form_widgets)
    return form_class


@login_required
@clan_required
def update_recurring_expense(request, pk):
    recurring_expense = get_object_or_404(RecurringExpense.objects, pk=pk)
    form_class = get_recurring_expense_form(request.user)
    next = request.GET.get('next', reverse("expense:recurring_list"))
    list_params = request.session.get(RECURRING_EXPENSE_PARAMS_KEY)
    if list_params:
        next = f"{next}?{urlencode(list_params)}"
    
    if request.method == "POST":
        form = form_class(request.POST, instance=recurring_expense)
        if form.is_valid():
            rexpense = form.save(commit=False)
            rexpense.next_occurrence = get_next_occurrence(rexpense.recurrences,
                                                           time=rexpense.time,
                                                           time_zone=rexpense.time_zone)
            rexpense.save()
            messages.add_message(request, messages.SUCCESS, _("expense-created"))
            return redirect(form.cleaned_data['next'])
    else:
        form = form_class(initial={'next': next}, instance=recurring_expense)
    context = {
        'form': form,
        'next': next,
        'pk': pk,
    }
    return render(request, "recurring_expense/update.html", context)


# This should be called only internally
def post_current_expenses(request):
    create_current_expenses()
    return "{}"

datini/expense/templates/recurring_expense/create.html
  {% extends "expense/base.html" %}
{% load ftl %}
{% load django_bootstrap5 %}

{% block head %}
	{{ block.super }}
  <script src="{% url 'javascript-catalog' %}"></script>
{% endblock %}

{% block main %}
  {% ftlconf mode="server" bundle="expense.fluent.bundle" %}
  <div class="container" id="container">
    <div class="row align-items-center justify-content-center">
      <div class="col col-12 col-md-8 py-3">
        <h2>{% ftlmsg 'expense-create' %}</h2>
        <form method="post">
          {% csrf_token %}
          {{ form.media }}
          {% bootstrap_field form.next %}
          {% bootstrap_field form.who %}
          {% bootstrap_field form.what %}
          <div class="mb-3 input-group">
            {% bootstrap_label form.how_much.label %}
            {% bootstrap_field form.how_much show_label="skip" wrapper_class="input-group" %}
          </div>
          {% bootstrap_field form.category %}
          <div class="clearfix">
            {% bootstrap_field form.recurrences %}
          </div>

          <details class="mt-3">
            <summary>{% ftlmsg "expense-recurrences-time" %}</summary>
            <p class="form-text">
              {% ftlmsg "expense-recurrences-time-help" recurrence_time=default_recurrence_time %}
            </p>
            <div class="row row cols-2">
              <div class="col">{% bootstrap_field form.time %}</div>
              <div class="col">{% bootstrap_field form.time_zone %}</div>
            </div>
          </details>

          <div class="mt-4 d-flex align-items-center">
            <div class="flex-grow-1">
              <button type="submit" class="btn btn-primary">
                {% ftlmsg 'expense-create-action' %}
              </button>
            </div>
            {% block form_nav %}
            <div>
              <a href="{{ next }}">{% ftlmsg 'expense-back' %}</a>
            </div>
            {% endblock %}
          </div>
        </form>
      </div>
    </div>
  </div>
  <script>
    document.getElementById("id_how_much_0").onfocus = e => e.target.select();
    {
      let userTimeZone
      try {
        userTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
      } catch(error) {
        console.error("Unable to infer userTimeZone from Intl");
      }
      if (userTimeZone) {
        let optionElement = document.getElementById('id_time_zone').querySelector(`option[value="${userTimeZone}"]`)
        if (optionElement) {
          optionElement.selected = true;
        }
      }
    }
  </script>
{% endblock %}

datini/expense/templates/recurring_expense/list.html
{% extends "expense/base.html" %}
{% load static %}
{% load ftl %}
{% load django_bootstrap5 %}

{% block head %}
	{{ block.super }}
  <script src="{% static "expense/expense.js" %}"></script>
{% endblock %}

{% block header %}
  {{ block.super }}
  {% bootstrap_messages %}
{% endblock header %}

{% block main %}
  {% ftlconf mode="server" bundle="expense.fluent.bundle" %}
  <div class="container py-3">
    <table class="table datini expense compact">
      <caption class="position-sticky bottom-0">
        <div class="row align-items-center datini-action-drawer">
          <div class="col col-4 text-center">
            <a href="{% url "expense:home" %}" class="link-alabaster link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001q.044.06.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1 1 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
              </svg><br>
              {% ftlmsg "expense-nav-home" %}
            </a>
          </div>
          <div class="col col-4 text-center">
            <a class="link-alabaster link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar3" viewBox="0 0 16 16">
                <path d="M14 0H2a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2M1 3.857C1 3.384 1.448 3 2 3h12c.552 0 1 .384 1 .857v10.286c0 .473-.448.857-1 .857H2c-.552 0-1-.384-1-.857z"/>
                <path d="M6.5 7a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-9 3a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2m3 0a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/>
              </svg><br>
              {% ftlmsg "expense-nav-recurring" %}
            </a>
          </div>
          <div class="col col-4 text-center">
            <a href="{% url "expense:recurring_create" %}" class="btn btn-alabaster text-avocado">
              {% ftlmsg "expense-nav-create" %}
            </a>
          </div>
        </div>
      </caption>
      <thead>
      <tr>
        <th>{% ftlmsg 'expense-when' %}</th>
        <th>{% ftlmsg 'expense-who' %}</th>
        <th>{% ftlmsg 'expense-what' %}</th>
        <th>{% ftlmsg 'expense-category' %}</th>
        <th class="how-much">{% ftlmsg 'expense-how_much' %}</th>
      </tr>
      </thead>
      <tbody>
      {% ftlmsg "expense-what-na" as NA %}
      {% for expense in item_list %}
        <tr>
          <td class="when">{{ expense.next_occurrence }}</td>
          <td class="who">{{ expense.who }}</td>
          <td class="what">
            <a href="{% url "expense:recurring_update" expense.pk %}">
              {{ expense.what|default:NA }}
            </a>
          </td>
          <td class="category">{{ expense.get_category_display }}</td>
          <td class="how-much">{{ expense.how_much }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  <p class="text-center">
  </p>
  </div>
{% endblock %}

datini/expense/templates/recurring_expense/update.html
{% extends "expense/base.html" %}
{% load ftl %}
{% load django_bootstrap5 %}

{% block head %}
	{{ block.super }}
  <script src="{% url 'javascript-catalog' %}"></script>
{% endblock %}

{% block main %}
  {% ftlconf mode="server" bundle="expense.fluent.bundle" %}
  <div class="container" id="container">
    <div class="row align-items-center justify-content-center">
      <div class="col col-12 col-md-8 py-3">
        <h2>{% ftlmsg 'expense-update' %}</h2>
        <form method="post" id="recurring_expense_form" class="clearfix">
          {% csrf_token %}
          {{ form.media }}
          {% bootstrap_field form.next %}
          {% bootstrap_field form.who %}
          {% bootstrap_field form.what %}
          <div class="mb-3 input-group">
            {% bootstrap_label form.how_much.label %}
            {% bootstrap_field form.how_much show_label="skip" wrapper_class="input-group" %}
          </div>
          {% bootstrap_field form.category %}
          <div class="clearfix">
            {% bootstrap_field form.recurrences %}
          </div>

          <details class="mt-3">
            <summary>{% ftlmsg "expense-recurrences-time" %}</summary>
            <div class="row row cols-2 my-2">
              <div class="col">{% bootstrap_field form.time %}</div>
              <div class="col">{% bootstrap_field form.time_zone %}</div>
            </div>
          </details>

        </form>
        <div class="mt-4 d-flex align-items-center">
          <div class="flex-grow-1">
            <button type="submit" class="btn btn-primary" form="recurring_expense_form">
              {% ftlmsg 'expense-update-action' %}
            </button>
          </div>
          {% block form_nav %}
          <div>
            <a href="{{ next }}">{% ftlmsg 'expense-back' %}</a>
          </div>
          {% endblock %}
        </div>
      </div>
    </div>
  </div>
  <script>
      document.getElementById("id_how_much_0").onfocus = e => e.target.select();
      {
        let userTimeZone
        try {
          userTimeZone = Intl.DateTimeFormat().resolvedOptions().timeZone;
        } catch(error) {
          console.error("Unable to infer userTimeZone from Intl");
        }
        if (userTimeZone) {
          let optionElement = document.getElementById('id_timezone').querySelector(`option[value="${userTimeZone}"]`)
          if (optionElement) {
            optionElement.selected = true;
          }
        }
      }
  </script>
{% endblock %}